spring:
  data:
    mongodb:
      host: 10.200.1.171
      username: admin
      password: meiya@2019
      database: morphia_test
      port: 27017
morphia: 
  mapperPackage: com.example.demo.entity
